meta_product_name: "Catching App"
meta_title: "We have some catching app to do!"
meta_description: "Find a time that works for everyone, shown in everyone's own time zone. No sign-up needed."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
